#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

####################################
######   Optional Features    ######
####################################
smooth-scroll: false

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

# This is your site title
title: The Autumn Almanacs
# Website language
lang: en-US
# Header Title
header-title: Neu in Bochum!
# Header Tagline
headter-tagline: 

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Download Now
  url: https://themeforest.net/collections/6069390-sera

# Secondary Buttons
header-secondary-button:
  title: Discover More
  url: http://themeforest.net/user/ohkimur

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: stephan_jacobs@gmx.de

collections: 
  - products

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: https://themeforest.net/collections/6069390-sera

####################################
######  Global Social Links   ######
####################################
youtube: "https://www.youtube.com/channel/UCskLJPKM6gXXK6xtWi5fqtA"
pinterest: "#"
facebook: "https://www.facebook.com/share/1YywacV3fD/"
twitter: "#"
instagram: "https://www.instagram.com/gtue.pruefstelle.bochum?igsh=NzZtcnBlbzdrdG80"
google-plus: "#"
vimeo: "#"


#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: Studio_7.jpg
  author-name: Stephan
  author-tagline: Blog Author
  author-info: Writes as web desginer current band information.


# Google Map JS api
key-api: YOUR_GOOGLE_MAP_API_KEY
map-text: Sera Google Map
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: RueMorgue666
  list-id: 15684726

####
#
# Hi you now use Sera - OnePage Jekyll Theme created by Ohkimur
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Über
about-description: Wir sind Ansprechpartner in Bochum und Umgebung, wenn es um Haupt- und Abgasuntersuchungen oder Änderungsabnahmen sowie weitere Servicedienstleistungen rund um zwei, drei, und vier Räder geht.
#####################################
#############  Features  ############
#####################################
features-title: Features
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:
  # Feature
  - title: Clean & Unique Design
    description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
    icon: pe-7s-vector

  # Feature
  - title: Professional Support
    description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
    icon: pe-7s-help2

  # Feature
  - title: Pixel Perfect
    description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
    icon: pe-7s-airplay

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Gallery
portfolio-description: We try to update the gallery section as soon we are getting new pics.

#
# Portfolio Grid
#
portfolio-categories:
portfolio:

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: []
    image: Logo_Gross3.PNG
    url: "#"
    text: "Logo Prüfstelle"

      # Portfolio Item
  - title: <span class="thin">era</span> Style
    categories: []
    image: Pruefstelle.jfif
    url: "#"
    text: "Foto Prüfstelle"



#####################################
##########  Core Features  ##########
#####################################
core-title: Core Features
core-description: We create something unique with the following mix

#
# Core Features Left
#
core-features-left:
  # Feature
  - name: Hauptuntersuchung (HU)
    description: Hauptuntersuchung (HU) inkl. Abgasuntersuchung gem. § 29 StVZO
    icon: pe-7s-world

  # Feature
  - name: Änderungsabnahmen gem. § 19 (3) StVZO
    description: psychedelic, flower power hippie atmosphere
    icon: pe-7s-leaf

  # Feature
  - name: Die amtlichen Schadstoffplaketten
    description: Optimized recordings with guest musicians
    icon: pe-7s-album

#
# Core Features Right
#
core-features-right:
  # Feature
  - name: Technischer Dienst
    description: Technischer Dienst
    icon: pe-7s-smile

  # Feature
  - name: Sachverständigenleistung
    description: unforgettable live performance with many suprises
    icon: pe-7s-speaker

  # Feature
  - name: Gasprüfung GSP/GAP/GWP
    description: trying to create something magic
    icon: pe-7s-magic-wand

  # Feature
  - name: Sicherheitsprüfung gemäß § 29 StVZO
    description: plug it in and enjoy it
    icon: pe-7s-plug

#####################################
########### Testimonials ############
#####################################
testimonials-title: Reviews
testimonials-description: Here you find some reviews of our first LP.

#
# Testimonials
#
testimonials:
  # Client
  - name: UNDERDOG Fanzine
    url: https://www.underdog-fanzine.de/2018/05/30/the-autumn-almanacs-all-work-and-no-play-makes-jack-a-dull-boy
    url-text: Review
    avatar: avatar-01.jpg
    cite: Time to dream peaceful, relax and cele  brate your knowledge!
    logo-img: underdog_logo.jpg

  # Client
  - name: Rocktimes
    url: https://www.rocktimes.info/the-autumn-almanacs-all-work-and-no-play-makes-jack-a-dull-boy-cd-review
    url-text: Review
    avatar: avatar-02.jpg
    cite: Remnants of the beat era mixed with psychedelic, flower power hippie atmosphere, sunshine pop and the first echoes of rock music and, thanks to the wind instruments, a touch of rhythm & blues.
    logo-img: rocktimes_logo.jfif

  # Client
  - name: Powermetal.de
    url: https://powermetal.de/review/review-Autumn_Almanacs__The/All_Work_And_No_Play_Makes_Jack_A_Dull_Boy,34935.html
    url-text: Review
    avatar: avatar-03.jpg
    cite: If a band can unite friends of many classic genres without sounding artificial or implausible, that means something - and the Cologne-based members managed to do that on "All Work And No Play Makes Jack A Dull Boy".
    logo-img: powermetal_logo.png


#####################################
############# Our Blog ##############
#####################################
blog-title: Our Blog
blog-description: Get the current news from us.

#####################################
############### Team ################
#####################################
team-title: Meet The Band
team-description: You can contact us also personally.



#####################################
############  Audio      ############
#####################################
audio-title: Audio

#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Table
pricing-description: Buy our LPs (Shipping Costs for EU included) and check our songs on Spotify, iTunes, Apple Music, Youtube, Deezer, etc.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: "#"

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: "#"

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: "#"

#####################################
############   Contact   ############
#####################################
contact-title: Kontaktiere mich
contact-description: Falls Du mich direkt erreichen möchtest oder Fragen hast, fülle bitte das Formular aus

#####################################
#############   Footer   ############
#####################################
footer-description: Copyright 2025 Marcus Brand. Designed by Stephan Jacobs. All right reserved
footer-copyright-text: Marcus Brand
footer-copyright-url: https:/www.xn--gt-prfung-brand-0vbd.de/
footer-copyright-year: 2025
